project:
  type: book

book:
  title: "PhD Meeting Notes"
  author: "Krisanat Anukarnsakulchularp"
  chapters:
    - index.qmd
    - network-experiment.qmd
    - caribou-analysis.qmd    
    - literature-review.qmd

bibliography: references.bib

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt



