# Literature Review

## Graphical discovery in stochastic actor-oriented models for social network analysis - Chapter 4

Many R packages can manipulate network objects. However, they mainly focused on analysing network data and not necessarily on rendering visualisations of networks. Visualising network data using packages such as `igraph`, `sna`, and `network` requires much extra work if one is used to working with a data structure like vectors, data frames, or arrays. This chapter provides three different approaches to network visualisation through **ggplot2 wrappers**. The first is a function, `ggnet2`, from the `ggally` package that acts as a wrapper around a network object to create a `ggplot2` graph. The second package, `geomnet`, combines all network pieces (nodes, edges, and labels) into a single **geom** and is intended to look the most like other **ggplot2 geoms** in use. The final package, `ggnetwork`, performs some data manipulation and aliases other **geoms** to layer the different network aspects on top of the other. Each of these packages also has different ways of dealing with the data structure.

For geomnet, it combines two sources of information, node description and the relationship between nodes (vertices), into one dataset using the fortify s3 methods. The supported classes are "network" from `sna` and `network` packages, "igraph" from the `igraph` package, "adjmat", and "edgedf" (classes from `geomnet`). It is then passed on to the ggplot2 to draw the network data. On the other hand, `ggnet2` and `ggnetwork` internally translate a network object into a data frame suitable for plotting with **ggplot2**, then apply network-related aesthetic operations to that data frame.

## Hospital Transfer Network Structure as a Risk Factor for Clostridium defficile Infection
